name: Build Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'

    - name: Install API dependencies
      run: npm install --prefix api

    - name: Install UI dependencies
      run: npm install --prefix ui

    - name: Install Electron dependencies
      run: npm install --prefix electron

    - name: Run build script
      run: node build.mjs